picme/base/urls.py
from . import views

from django.conf.urls import include, url


app_name = 'base'


urlpatterns = [
    url(r'^test/$', views.test, name='test'),
]

picme/picme/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from posts import views as posts_view

urlpatterns = [
    url(r'^$', posts_view.show_post_list, name='posts_index'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('userena.urls')),
    url(r'^accounts/', include('chat.urls')),
    url(r'^base/', include('base.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^address/', include('address.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^dialogs/', include('private_chat.urls', namespace="private_chat")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

picme/posts/urls.py
from . import views

from django.conf.urls import url

app_name = 'posts'

urlpatterns = [
	url(r'^$', views.show_post_list, name='index'),

	url(r'^list_by_pop/?$', views.show_post_list_by_pop, name='pop'),

	url(r'^list_by_comment/?$', views.show_post_list_by_Comment, name='comment'),

	url(r'^search/?$', views.search_by_location, name='search'),

	url(r'^new/?$', views.new_post, name='new'),

	url(r'^user_posts/?$', views.UserPostListView.as_view(), name="user_posts"),

	url(r'^(?P<post_id>[0-9]+)/?$', views.post_detail, name='detail'),

	url(r'^delete_post/(?P<post_id>[0-9]+)/?$', views.delete_post, name='delete_post'),

	url(r'^like_post/(?P<post_id>[0-9]+)/?$', views.like_post, name='like_post'),

	url(r'^post_photo/(?P<post_id>[0-9]+)/?$', views.get_post_photo, name='get_post_photo'),

	url(r'^recover_post/(?P<post_id>[0-9]+)/?$', views.recover_post, name='recover_post'),

	url(r'^follow_posts/?$', views.follow_posts, name='follow_posts'),

	url(r'^loc_post/(?P<username>\w+)/?$', views.get_post_list_by_location, name='post_by_location'),

	# get all posts, and pack into json
	url(r'^all_posts_for_map/?$', views.get_all_posts_for_map, name='all_post_for_map'),

	url(r'^get_comment/(?P<post_id>[0-9]+)/?$', views.get_comments, name='getcomment'),

	url(r'^add_comment/(?P<post_id>[0-9]+)/?$', views.add_comments, name='addcomment'),

	url(r'^edit/(?P<post_id>[0-9]+)/?$', views.goto_editor, name='editor'),

	url(r'^edit_photo/(?P<post_id>[0-9]+)/?$', views.goto_photo_editor, name='photo_editor'),

	url(r'^update_photo/(?P<post_id>[0-9]+)/?$', views.update_photo, name='update_photo'),

]

picme/base/models.py
from django.db import models

# Create your models here.

picme/base/views.py
from django.shortcuts import render

# Create your views here.
def test(request):
	return render(request, 'base/base.html', {})

picme/base/templates/base/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>      

	<title>{% block title %}{% endblock %}</title>
	
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	
	{% block meta %}{% endblock %}
	
	<link rel="stylesheet" type="text/css" href="{% static 'base/css/base.css' %}">
</head>
 

<body id="{% block body_id %}{% endblock %}" class=" {% block body_class %}{% endblock %}">
	<header>
		{% block header %}
            {% include "base/navbar.html" %}
		{% endblock %}
	</header>
	
	<main>
		{% block body %}

			<div class="container">
				{% block content %}
				
				{% endblock %}
			</div>
			
		{% endblock %}
	</main>

	{% block footer %}
  		{% include "base/footer.html" %}
	{% endblock %}

</body>

<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/js/materialize.min.js"></script>
<script src="{% static 'base/js/base.js' %}"></script>


{% block script %}{% endblock %}        

</html>

picme/base/templates/base/footer.html
<footer class="page-footer black">
	<div class="footer-copyright ">
		<div class="container">
		© 2017 Copyright
		</div>
	</div>
</footer>

picme/base/templates/base/navbar.html
{% load static %}

<nav class="black">
    <div class="nav-wrapper container">
        <a href="{% url 'posts_index' %}" class="brand-logo">PicMe</a>

        <ul class="right hide-on-med-and-down">
            <li>
                <a href="{% url 'posts_index' %}">
                    Photos
                </a>
            </li>
            <li>
                <a href="{% url 'posts:follow_posts' %}">
                    Follower Posts
                </a>
            </li>
            <li>
                <a href="{% url 'posts:new' %}">
                    Create Post
                </a>
            </li>
            <li>
                <a class="dropdown-button" href="#" data-activates="dropdown1" data-beloworigin="true" data-hover="true" onmouseover="unread_message()">
                    Unread Message
                    <i class="material-icons right">arrow_drop_down</i>
                </a>
            </li>

            <!-- Dropdown Structure -->
            <ul id="dropdown1" class="dropdown-content"></ul>

            {% if user.is_authenticated %}
                <li></li>
                <li>
                    <a href="/accounts/{{ user.username }}">
                        <img src="{{ user.user_profile.get_mugshot_url }}" class="avatar circle nav-avatar"/>
                        {{ user.user_profile.nick_name }}
                    </a>
                </li>
                <li><a href="/accounts/signout">Sign out</a></li>
            {% else %}
                <li><a href="/accounts/signup">Register</a></li>
                <li><a href="/accounts/signin">Login</a></li>
            {% endif %}
        </ul>

        <ul id="nav-mobile" class="side-nav" style="left: 0px;">
            <li>
                <a href="{% url 'posts_index' %}">
                    Photos
                </a>
            </li>
            <li>
                <a href="{% url 'posts:follow_posts' %}">
                    Follower Posts
                </a>
            </li>

            <div class="divider"> </div>
            <li>
                <a href="{% url 'posts:new' %}">
                    Create Post
                </a>
            </li>
            <div class="divider"> </div>
            <li>
                <a class="dropdown-button" href="#" data-activates="dropdown1" data-beloworigin="true" data-hover="true" onmouseover="unread_message()">
                    Unread Message
                    <i class="material-icons right">arrow_drop_down</i>
                </a>
            </li>

            <!-- Dropdown Structure -->
            <!-- <ul id="dropdown1" class="dropdown-content"></ul> -->

            <div class="divider"> </div>
            {% if user.is_authenticated %}
                <li></li>
                <li>
                    <a href="/accounts/{{ user.username }}">
                        <img src="{{ user.user_profile.get_mugshot_url }}" class="avatar circle nav-avatar"/>
                        {{ user.user_profile.nick_name }}
                    </a>
                </li>
                <li><a href="/accounts/signout">Sign out</a></li>
            {% else %}
                <li><a href="/accounts/signup">Register</a></li>
                <li><a href="/accounts/signin">Login</a></li>
            {% endif %}
        </ul>

        <a href="" data-activates="nav-mobile" class="button-collapse"><i class="material-icons white-text">menu</i></a>
    </div>
</nav>