picme/base/urls.py
from . import views

from django.conf.urls import include, url


app_name = 'base'


urlpatterns = [
    url(r'^test/$', views.test, name='test'),
]

picme/picme/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from posts import views as posts_view

urlpatterns = [
    url(r'^$', posts_view.show_post_list, name='posts_index'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('userena.urls')),
    url(r'^accounts/', include('chat.urls')),
    url(r'^base/', include('base.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^address/', include('address.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^dialogs/', include('private_chat.urls', namespace="private_chat")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

picme/posts/urls.py
from . import views

from django.conf.urls import url

app_name = 'posts'

urlpatterns = [
	url(r'^$', views.show_post_list, name='index'),

	url(r'^list_by_pop/?$', views.show_post_list_by_pop, name='pop'),

	url(r'^list_by_comment/?$', views.show_post_list_by_Comment, name='comment'),

	url(r'^search/?$', views.search_by_location, name='search'),

	url(r'^new/?$', views.new_post, name='new'),

	url(r'^user_posts/?$', views.UserPostListView.as_view(), name="user_posts"),

	url(r'^(?P<post_id>[0-9]+)/?$', views.post_detail, name='detail'),

	url(r'^delete_post/(?P<post_id>[0-9]+)/?$', views.delete_post, name='delete_post'),

	url(r'^like_post/(?P<post_id>[0-9]+)/?$', views.like_post, name='like_post'),

	url(r'^post_photo/(?P<post_id>[0-9]+)/?$', views.get_post_photo, name='get_post_photo'),

	url(r'^recover_post/(?P<post_id>[0-9]+)/?$', views.recover_post, name='recover_post'),

	url(r'^follow_posts/?$', views.follow_posts, name='follow_posts'),

	url(r'^loc_post/(?P<username>\w+)/?$', views.get_post_list_by_location, name='post_by_location'),

	# get all posts, and pack into json
	url(r'^all_posts_for_map/?$', views.get_all_posts_for_map, name='all_post_for_map'),

	url(r'^get_comment/(?P<post_id>[0-9]+)/?$', views.get_comments, name='getcomment'),

	url(r'^add_comment/(?P<post_id>[0-9]+)/?$', views.add_comments, name='addcomment'),

	url(r'^edit/(?P<post_id>[0-9]+)/?$', views.goto_editor, name='editor'),

	url(r'^edit_photo/(?P<post_id>[0-9]+)/?$', views.goto_photo_editor, name='photo_editor'),

	url(r'^update_photo/(?P<post_id>[0-9]+)/?$', views.update_photo, name='update_photo'),

]

picme/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from address.models import State, City


def post_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'post_images/{0}/{1}'.format(instance.user.username, filename)


class TimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# Post Module
class Post(TimeStampedModel):
    # basic
    post_title = models.CharField(
        max_length=200,
        null=False
    )

    post_description = models.TextField(max_length=160)

    # picture
    post_picture = models.FileField(
        null=False,
        blank=False,
        upload_to=post_directory_path
    )

    # The location of the picture
    post_state = models.ForeignKey(
        State,
        related_name='state'
    )

    post_city = models.ForeignKey(
        City,
        related_name='city'
    )

    # user who creates the post
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    likes = models.ManyToManyField(User, related_name='likes_posts', blank=True)

    show = models.BooleanField(default=True)

    numberOfLikes = models.PositiveIntegerField(default=0)

    file_type = models.CharField(max_length=10, null=True)

    numberOfComment = models.PositiveIntegerField(default = 0)

    def __str__(self):
        return self.post_title

class Comment(TimeStampedModel):
    content = models.CharField(max_length=160, null=False, default=None)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    belong_post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None)

picme/posts/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from .models import Post
from address.models import City
from django.utils.translation import ugettext as _

import logging

logger = logging.getLogger(__name__)


MAX_UPLOAD_SIZE = 20971520


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = (
			'post_title',
			'post_description',
			'post_picture',
			'post_state',
			'post_city'
		)

		labels = {
			"post_title": _("Title"),
			"post_description": _("Description"),
			"post_picture": _("Upload")
		}

	def __init__(self, *args, **kwargs):
		super(PostForm, self).__init__(*args, **kwargs)

		self.initial['post_state'] = 10101010101
		self.fields['post_state'].empty_label = "Please Choose"

		self.fields['post_city'].choices = []

	def clean_post_picture(self):
		file = self.cleaned_data['post_picture']

		supported_image_type = ['image/jpeg', 'image/pjpeg', 'image/png', 'image/gif']

		supported_video_type = ['video/mp4', 'video/webm', 'video/ogg']

		if not file.content_type or not (file.content_type in supported_video_type or file.content_type in supported_image_type):
			raise forms.ValidationError(_('File type is not supported'))

		if file.size > MAX_UPLOAD_SIZE:
			raise forms.ValidationError(_('File too big (max size is {0} bytes)'.format(MAX_UPLOAD_SIZE)))
		return file

class EditPostForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ['post_title','post_description','post_state','post_city']

	def __init__(self , *args, **kwargs):
		city = kwargs.pop('city', None)
		super(EditPostForm, self).__init__(*args, **kwargs)
		if city :
			logger.debug("[city_id] = " + str(city))
			self.fields['post_city'].choices = [(city.id, city.name)]

picme/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.db.models import Q
from .forms import PostForm, EditPostForm
from django.contrib.auth.models import User
from .models import Post, Comment
from address.models import State, City
from django.views.decorators.csrf import ensure_csrf_cookie
from base64 import b64decode
from django.core.files.base import ContentFile

from django.http import HttpResponse, HttpResponseRedirect, Http404, HttpResponseForbidden

from django.core import serializers
import re

import json
import logging
import geoip2.database

logger = logging.getLogger(__name__)


@login_required
def new_post(request):

	if request.method == 'POST':
		current_user = request.user
		form = PostForm(request.POST, request.FILES or None, instance=Post(user=current_user))

		if form.is_valid():
			post = form.save(commit=False)
			post.user = request.user
			post.file_type = request.FILES.get('post_picture').content_type.split('/')[0]
			post.save()
			return HttpResponseRedirect('/posts/'+str(post.id)+"/")
		else:
			form = PostForm(request.POST)
			dict_list = {
				'user': request.user,
				'form': form,
				'message': 'New post created successfully'
			}
			return render(request, 'posts/new.html', dict_list)
	else:
		form = PostForm()
		dict_list = {
			'user': request.user,
			'form': form,
			'message': 'New post created successfully'
		}
		return render(request, 'posts/new.html', dict_list)


# class IndexView(ListView):
# 	template_name = 'posts/index.html'
# 	context_object_name = 'posts'

# 	@method_decorator(login_required)
# 	def dispatch(self, request, *args, **kwargs):
# 		return super(ListView, self).dispatch(request, *args, **kwargs)

# 	def get_queryset(self):
# 		return Post.objects.filter(show=True).order_by('-created')


@login_required
def show_post_list(request):
	posts = Post.objects.filter(show=True).order_by('-created')

	current_user = request.user

	like_posts = current_user.likes_posts.all()

	ip = request.META['REMOTE_ADDR']
	# ip = '71.60.32.90'
	reader = geoip2.database.Reader('address/GeoLite2-City.mmdb')
	response = reader.city(ip)
	city = (str(response.city.name)).upper()
	try:
		posts_nearby = Post.objects.filter(show=True, post_city=City.objects.get(name=city)).order_by('-numberOfLikes')[:3]
	except City.DoesNotExist:
		posts_nearby = None
	context = {
		'posts': posts,
		'like_posts': like_posts,
		'posts_nearby': posts_nearby,
	}

	reader.close()

	return render(request, 'posts/index.html', context)



@login_required
def show_post_list_by_pop(request):
	posts = Post.objects.filter(show=True).order_by('-numberOfLikes')

	current_user = request.user

	like_posts = current_user.likes_posts.all()

	context = {
		'posts': posts,
		'like_posts': like_posts,
	}

	return render(request, 'posts/index.html', context)

@login_required
def show_post_list_by_Comment(request):
	posts = Post.objects.filter(show=True).order_by('-numberOfComment')

	current_user = request.user

	like_posts = current_user.likes_posts.all()

	context = {
		'posts': posts,
		'like_posts': like_posts,
	}

	return render(request, 'posts/index.html', context)


@login_required
def post_detail(request, post_id):

	post = get_object_or_404(Post, id=post_id)

	if not post.show:
		raise Http404('Post does not exist')

	context = {'post': post}

	return render(request, 'posts/detail.html', context)


# List all of the Posts of the user
class UserPostListView(ListView):
	template_name = 'posts/userposts.html'
	context_object_name = 'posts'

	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		return super(ListView, self).dispatch(request, *args, **kwargs)

	def get_queryset(self):
		return Post.objects.filter(
			Q(user=self.request.user.user_profile) &
			Q(show=True))


@login_required
def delete_post(request, post_id):

	if request.method == 'GET':
		raise Http404('Can\'t delete post using GET method')

	message = ''

	logging.debug("[post_id] = " + str(post_id))

	if request.method == 'POST':

		post = get_object_or_404(Post, id=post_id)

		post_user = post.user
		current_user = request.user

		if not post.show:
			raise Http404('Post does not exist')

		if post_user == current_user:
			post = Post.objects.get(id=post_id)
			post.show = False
			post.save()
			message = 'Delete Successfully'
		else:
			message = 'The post does not belong to you'

	posts = Post.objects.filter(show=True)
	context = {
		'posts': posts,
		'user': request.user,
		'message': message
	}

	return render(request, 'posts/index.html', context)


@login_required
def like_post(request, post_id):

	current_user = request.user
	posts = Post.objects.filter(show=True)
	post = Post.objects.get(id=post_id)

	if not post.show:
		raise Http404('Post does not exist')

	context = {
		'user': current_user,
		'posts': posts
	}

	if current_user in post.likes.all():
		post.likes.remove(current_user)
		post.numberOfLikes = post.numberOfLikes - 1
		post.save()
	else:
		post.likes.add(current_user)
		post.numberOfLikes = post.numberOfLikes + 1
		post.save()

	return render(request, 'posts/index.html', context)


@login_required
def search_by_location(request):
	try:
		key = request.GET.get('key')
	except:
		key = ''
	if key != '':

		try:
			state_keys = State.objects.filter(name__icontains=key)
		except State.DoesNotExist:
			state_keys = []

		try:
			city_keys = City.objects.filter(name__icontains=key)
		except City.DoesNotExist:
			city_keys = []

		try:
			post_list = Post.objects.filter(
				(Q(post_state__in=state_keys) |
				Q(post_city__in=city_keys)) &
				Q(show=True)
			).order_by('-created')
		except Post.DoesNotExist:
			post_list = []

	else:
		post_list = Post.objects.filter(show=True).order_by('-created')

	context = {
		'user': request.user,
		'posts': post_list
	}
	return render(request, 'posts/index.html', context)


@login_required
def get_post_photo(request, post_id):
	post = Post.objects.get(id=post_id)

	if not post.show:
		raise Http404('Post does not exist')

	return HttpResponse(post.post_picture, content_type=post.content_type)


@login_required
def recover_post(request, post_id):

	if not request.method == 'POST':
		raise Http404('Can not recover post using GET method')
	else:
		post = get_object_or_404(Post, id=post_id)
		if not post.user == request.user:
			message = 'The post does not belong to you'
			return render(request, 'posts/error_page.html', {'message': message})
		if post.show:
			message = 'Can not recover an existed post'
			return render(request, 'posts/error_page.html', {'message': message})

		post.show = True
		post.save()

		context = {
			'posts': Post.objects.filter(show=True).order_by('-created'),
			'user': request.user,
			'message': 'Recover post successfully'
		}

		return render(request, 'posts/index.html', context)


@login_required
def follow_posts(request):

	current_user = request.user
	user_profile = current_user.user_profile
	followers = user_profile.follows.all()

	follow_posts = []

	for follower in followers:
		posts = Post.objects.filter(
			Q(user=follower) &
			Q(show=True)
			)
		follow_posts.extend(posts)

	follow_posts.sort(key=lambda r: r.created, reverse=True)

	like_posts = current_user.likes_posts.all()

	context = {
		'posts': follow_posts,
		'like_posts': like_posts,
	}

	return render(request, 'posts/follow_posts.html', context)


@login_required
def get_post_list_by_location(request, username):
	user = User.objects.get(username=username)
	posts = Post.objects.filter(user=user, show=True)

	post_dic = {}
	json_list = list()

	for post in posts:
		city = post.post_city
		loc_post = post_dic.get(city)

		if loc_post is None:
			post_dic[city] = [post]
		else:
			post_dic[city].append(post)

		for city, post_list in post_dic.items():
			json_list.append(([city.name], [city.state], [city.latitude], [city.longitude], [len(post_list)]))

	return HttpResponse(json.dumps(json_list), content_type='application/json')


def get_all_posts_for_map(request):
	posts = Post.objects.filter(show=True)

	post_dic = {}
	json_list = list()

	for post in posts:
		city = post.post_city
		loc_post = post_dic.get(city)

		if loc_post is None:
			post_dic[city] = [post]
		else:
			post_dic[city].append(post)

		for city, post_list in post_dic.items():
			json_list.append(([city.name], [city.state], [city.latitude], [city.longitude], [len(post_list)]))

	return HttpResponse(json.dumps(json_list), content_type='application/json')


@login_required
def get_comments(request, post_id):
	post = Post.objects.get(id = post_id)
	comments = Comment.objects.filter(belong_post = post)
	response_text = construct_json(request, comments)
	return HttpResponse(response_text, content_type='application/json')

@login_required
def add_comments(request, post_id):
	if request.POST['content'] and not re.match('^\s*$', request.POST['content']):
		post = Post.objects.get(id=post_id)
		comment = Comment(content = request.POST['content'], sender = request.user, belong_post = post)
		comment.save()
		comments = Comment.objects.filter(id = comment.id)
		post.numberOfComment = post.numberOfComment + 1
		post.save()

		response_text = construct_json(request, comments)
		return HttpResponse(response_text, content_type='application/json')

def construct_json(request,items):
	r = '['
	for item in items:
		r = r + '{"pk": ' + str(item.id) + ', '
		r = r + '"content": "' + item.content + '", '
		r = r + '"time": "' + str(item.created)[0:len(str(item.created))-13] + '", '
		r = r + '"name": "' + item.sender.username + '"}, '
	if (len(items) != 0):
		r = r[0:len(r) - 2]
	r = r + ']'
	return r

#@login_required
#def comments(request, post_id):
#	post = Post.objects.get(id=post_id)
#
#	if request.method == 'GET':
#		context = {
#			'post': post
#		}
#
#		return render(request, 'posts/comment.html', context)

@login_required

picme/posts/templates/posts/detail.html
{% extends 'base/base.html' %}
{% load static %}
	
{% block title %}{{ post.post_title }}{% endblock %}

{% block content_title %}{% endblock %}

{% block meta %}
<link rel="stylesheet" type="text/css" href="{% static 'posts/css/detail.css' %}" media="screen,projection">
{% endblock %}   

{% block content %}
<div class="row">
	<div class="col s12 m8 offset-m2">
		<div class="card">
			<!-- <div class="card-image">
					<img src="{{ post.post_picture.url }}">
					<span class="card-title">{{ post.post_title }}</span>
			</div> -->
            <div class="card-image">
    			{% if post.file_type == 'image' %}
	    			<img class="materialboxed" src="{{ post.post_picture.url }}" width="100%">
    			{% elif post.file_type == 'video' %}
        			<!-- <video class="responsive-video" width="100%" controls>
            			<source src="{{ post.post_picture.url }}" type="video/mp4">
            			Your browser does not support HTML5 video.
        			</video> -->
        			<div class="video-container">
			        	<iframe width="100%"  src="{{ post.post_picture.url }}" frameborder="0" allowfullscreen></iframe>
			      	</div>
    			{% endif %}
            
            </div>
			<div class="card-content">
				<span class="card-title">{{ post.post_title }}</span>

				<br/><div class="divider"></div><br/>

				<div>
					<p>{{ post.post_description }}</p>
				</div>

				<br/><div class="divider"></div><br/>
				
				<div>
					<div class="chip grey lighten-4">
						<a href="/accounts/{{ post.user.username }}">
							<img src="{{ post.user.user_profile.get_mugshot_url }}"  alt = "Userena Mugshot">
							{{ post.user.username }}
						</a>
					</div>

					<div class="chip ">{{ post.post_state}}</div>
					&nbsp;
					<div class="chip ">{{ post.post_city}}</div>

				</div>

				<br/><div class="divider"></div><br/>

			
				<div>
					<div >
						<i class="material-icons">av_timer</i>
						{{ post.created}}
						
					</div> 
				</div>

				
				<br/><div class="divider"></div><br/>
				{% if post.user == request.user %}
				<div>
					<form id="delete_post_form" action="{% url 'posts:delete_post' post.id %}" method="post">
						{% csrf_token %}
						<a class="waves-effect waves-light right grey-text" href="\posts">
							<i class="fa fa-long-arrow-left small " aria-hidden="false"></i>
						</a>

						<a class="waves-effect waves-light   red-text" onclick="$('#delete_post_form').submit()">
							<i class="material-icons">delete</i>
						</a>

						<a class="waves-effect waves-light   red-text" onclick="goToEdit('/posts/edit/{{post.id}}')">
							<i class="material-icons">mode_edit</i>
						</a>

						<br>
					</form>
				</div>
				{% else %}
				<div>
					<a class="waves-effect waves-light right grey-text" href="\posts">
						<i class="fa fa-long-arrow-left small " aria-hidden="false"></i>
					</a>
				</div><br>
				{% endif %}
			</div>
		</div>
	</div>
</div>

<div class="row ">
	<div class="col s12 m8 offset-m2">
		<div class="card">

			<div class="card-content ">
			    <ul id = "comments" class="collection"></ol>
			</div>
			<div class="card-action">
				<input type="hidden" id="ID" value="{{ post.id }}">
				<input type="hidden" id="name" value="{{ request.user.username }}">
				<input type="text" id="content" placeholder="comment here">
				<button class="grey darken-2 waves-effect waves-light btn " onclick="addComment() ">comment</button>
			</div>
		</div>
	</div>
</div>


{% endblock %}

{% block script %}
	<!-- <script type="text/javascript" src="{% static 'posts/js/detail.js' %}"></script> -->
    <script src="{% static 'posts/js/comment.js' %}" type="text/javascript"></script>
    <script src="{% static 'posts/js/detail.js' %}" type="text/javascript"></script>
{% endblock %}

picme/posts/templates/posts/edit.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load static %}


<!-- static css file -->

{% block title %}Edit Post{% endblock %}

{% block content %}
	<div class="row">
		<div class="col s12 m8 offset-m2">
			<div class="card-panel">
				<form enctype="multipart/form-data" action='' method='POST' id="edit_form">
					{% csrf_token %}
					<div class="row">
						<div class="input-field col s9">
								{{form.post_title}}
								<label>{{form.post_title.label}}*</label>
						</div>
						<div class="col s3 red-text">{{form.post_title.errors}}</div>
					</div>

					<div class="row">
						<div class="input-field col s9">
							<textarea id="id_post_description" name="post_description" 
							class="materialize-textarea">{{form.post_description.value|default_if_none:""}}</textarea>	
							<label for="id_post_description">{{form.post_description.label}}*</label>
						</div>
						<div class="col s3 red-text">{{form.post_description.errors}}</div>
					</div>

					<div class="row">
						<div class="input-field col s9">
							{{ form.post_state }}
						</div>
						<div class="col s3 red-text">{{form.post_state.errors}}</div>
					</div>

					<div class="row">
						<div class="input-field col s9">
							{{ form.post_city }}
						</div>
						<div class="col s3 red-text">{{form.post_city.errors}}</div>
					</div>
					<p class="center-align">
						<a class="grey darken-2 waves-effect waves-light btn " onclick="$('#edit_form').submit()">submit</a>
						<a class="grey darken-2 waves-effect waves-light btn " onclick="goToEditPhoto('/posts/edit_photo/{{post.id}}')">Edit photo</a>
					</p>
				</form>
			</div>			
		</div>
	</div>
{% endblock %}


{% block script %}
	<script type="text/javascript" src="{% static 'posts/js/edit.js' %}"></script>
{% endblock %}

picme/posts/templates/posts/edit_photo.html
{% extends 'base/base.html' %}
{% load static %}
    
{% block title %}Edit photo{% endblock %}

{% block content_title %}{% endblock %}

{% block meta %}
    <link rel="stylesheet" type="text/css" href="{% static 'posts/css/detail.css' %}" media="screen,projection">
    <link rel="stylesheet" href="{% static 'posts/css/PhotoEditorReactUI.min.css' %}"/>
{% endblock %}   



{% block content%}
    <div class="row center-align">
        <div class="col s12">
            <div class="card">
                <div id="editor" style="width: 100%; height: 600px;"></div>
            </div>
        </div>
        <input type="hidden" id="ID" value="{{ post.id }}">
        <input type="hidden" id="photo_src" value="{{post.post_picture.url}}">
        <form action="" method="post">{% csrf_token %}</form>
    </div>
{% endblock %}


{% block script %}
    <script src="{% static 'posts/js/vendor/react.min.js' %}"></script>
    <script src="{% static 'posts/js/vendor/react-dom.min.js' %}"></script>
    <script src="{% static 'posts/js/PhotoEditorSDK.min.js' %}"></script>
    <script src="{% static 'posts/js/edit_photo.js' %}"></script>
    <script src="{% static 'posts/js/PhotoEditorReactUI.min.js' %}"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>
{% endblock %}


</body>
</html>

picme/posts/templates/posts/follow_posts.html
{% extends 'posts/index.html' %}

{% block title %}Follower Posts{% endblock %}

picme/posts/templates/posts/index.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}PicMe{% endblock %}
{% block meta %}
	<link rel="stylesheet" type="text/css" href="{% static 'posts/css/index.css' %}" media="screen,projection">
	<link rel="stylesheet" type="text/css" href="{% static 'posts/css/style.css' %}">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% endblock %}

{% block body %}
	<div id="index-banner" class="parallax-container">
		<div class="section no-pad-bot">
			<div class="container"></div>
		</div>
		<div class="parallax"><img src="{% static 'accounts/image/starry-night.jpg' %}"
								   alt="Unsplashed background img 1"></div>
	</div>

	<div class="container" id="post_list">

		<div class="row ">
			<div>
				<form action='/posts/search/' method='GET'>
					<div class="input-field col s12 m6 offset-m3">

						<input id="key" name="key" type="text">
						<label for="key">
							<i class="material-icons tiny">search</i>
							Search state or city
						</label>
					</div>
				</form>
			</div>
		</div>

		<div class="card-panel"> 
			<div id="map_wrapper">
				<div id="map_canvas" class="mapping"></div>
			</div>
		</div>

		<div class="divider"></div>

		{% if posts_nearby %}
		<div class="card-panel"> 
			<div class="row">
				<h5 class="center-align">Posts nearby</h5>
				{% for post in posts_nearby %}
					<div class="col s12 m4">
						<div class="card hoverable">
							{% include "posts/post_content.html" %}
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
		{% endif %}

		<div class="divider"></div>

		<div class="row">
			<div class="right">
				<label>Sort By:&nbsp;<a href="{% url 'posts:pop' %}">Popularity</a>&nbsp;&nbsp;&nbsp;<a href="{% url 'posts:comment' %}">Comment</a></label>
			</div>
		</div>

		<div class="row ">
			{% for post in posts %}
				<div class="col s12 m6 offset-m3">
					<div class="card hoverable">
						{% include "posts/post_content.html" %}
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}


{% block script %}
	<script type="text/javascript" src="{% static 'posts/js/index.js' %}"></script>
	<script type="text/javascript" src="{% static 'posts/js/like_post.js' %}" ></script>
	<script type="text/javascript" src="{% static 'posts/js/index_map.js' %}" ></script>
{% endblock %}

picme/posts/templates/posts/new.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load static %}


<!-- static css file -->

{% block title %}Create Post{% endblock %}

{% block content %}
<div class="row">
	<div class="col s12 m8 offset-m2">
		<div class="card-panel">
			<form enctype="multipart/form-data" action='' method='POST' id="new_form">
				{% csrf_token %}
				<div class="row">
					<div class="input-field col s9">
							{{form.post_title}}
							<label>{{form.post_title.label}}*</label>
					</div>
					<div class="col s3 red-text">{{form.post_title.errors}}</div>
				</div>

				<div class="row">
					<div class="input-field col s9">
						<textarea id="id_post_description" name="post_description" 
						class="materialize-textarea">{{form.post_description.value|default_if_none:""}}</textarea>	
						<label for="id_post_description">{{form.post_description.label}}*</label>
					</div>
					<div class="col s3 red-text">{{form.post_description.errors}}</div>
				</div>

				<div class="row">
					<div class="file-field input-field col s9">
						<div class="btn">
							<span>Post Picture</span>
							<input type="file" name="post_picture" required="">
						</div>
						<div class="file-path-wrapper">
							<input class="file-path validate" type="text">
						</div>
					</div>
					<div class="col s3 red-text">{{form.post_picture.errors}}</div>
				</div>

				<div class="row">
					<div class="input-field col s9">
						{{ form.post_state }}
					</div>
					<div class="col s3 red-text">{{form.post_state.errors}}</div>
				</div>

				<div class="row">
					<div class="input-field col s9">
						{{ form.post_city }}
					</div>
					<div class="col s3 red-text">{{form.post_city.errors}}</div>
				</div>

				<p class="center-align">
					<a class="grey darken-2 waves-effect waves-light btn " onclick="$('#new_form').submit()">submit</a>
				</p>
			</form>
		</div>			
	</div>
</div>
{% endblock %}


{% block script %}
	<script type="text/javascript" src="{% static 'posts/js/new.js' %}"></script>
{% endblock %}