picme/accounts/urls.py
from . import views

from django.conf.urls import url

from posts import views as posts_views

app_name = 'accounts'

urlpatterns = [

	# Follow another user
	url(r'^follow/$', views.follow, name='follow'),

	# UnFollow another user
	url(r'^unfollow/$', views.unfollow, name='unfollow'),

	# override this url in userena
	url(r'^$', views.toIndex, name='toIndex'),
]

picme/base/urls.py
from . import views

from django.conf.urls import include, url


app_name = 'base'


urlpatterns = [
    url(r'^test/$', views.test, name='test'),
]

picme/picme/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from posts import views as posts_view

urlpatterns = [
    url(r'^$', posts_view.show_post_list, name='posts_index'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('userena.urls')),
    url(r'^accounts/', include('chat.urls')),
    url(r'^base/', include('base.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^address/', include('address.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^dialogs/', include('private_chat.urls', namespace="private_chat")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

picme/private_chat/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.DialogListView.as_view(),
        name='dialogs_detail'
    ),
    url(
        regex=r'^$',
        view=views.DialogListView.as_view(),
        name='dialogs'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/read/$',
        view=views.set_read_message,
        name='set_read_message'
    ),
    url(
        regex=r'^unread/message/$',
        view=views.unread_message,
        name='unread_message'
    ),
]

picme/accounts/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.utils import timezone
from django.db import models

from django.utils.translation import ugettext as _
from userena.models import UserenaBaseProfile

class UserProfile(UserenaBaseProfile):
	gender_choices = (
		('M', 'Male'),
		('F', 'Female'),
		('U', 'Unknown')
	)

	user = models.OneToOneField(User, 
		on_delete=models.CASCADE,
		unique=True,
		verbose_name=_('user'),
		related_name='user_profile')

	nick_name = models.CharField(max_length=30)

	# User Description
	description = models.CharField(max_length=100,blank=True,null=True)
	
	gender = models.CharField(max_length=1, choices=gender_choices, default='U') 

	# Follow others
	follows = models.ManyToManyField(User, blank=True)

	def __str__(self):
		return self.user.username

	def save(self, *args, **kwargs):
		if not self.nick_name:
			self.nick_name = self.user.username
		super(UserProfile, self).save(*args, **kwargs)

picme/accounts/views.py
from django.shortcuts import render,reverse, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User

import logging
logger = logging.getLogger(__name__)

# Create your views here.
@login_required
def follow(request):
	logging.debug("[followId] = " + "Herere")
	if request.method == 'POST':
		followId = request.POST.get('followId')

		user = request.user
		user.user_profile.follows.add(followId)
		user.save()
		return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def unfollow(request):
	if request.method == 'POST':
		unfollowId = request.POST.get('unfollowId')
		logging.debug('[unfollowId] = ' + unfollowId )
		unfollowUser = get_object_or_404(User,id = unfollowId)
		user = request.user
		user.user_profile.follows.remove(unfollowUser)
		user.save()
		return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def toIndex(request):
	return redirect('posts:index')

picme/accounts/templates/userena/chatModal.html
<div id="chatmodal" class="modal">
    <div class="modal-content">
        <div class="chat-content scrollingDiv">
            <ol class="chat">
                {% for message in messages %}
                    {% if message.sender == request.user %}
                        <li class="self">
                            {% else %}
                        <li class="other">
                    {% endif %}
                <div class="avatar">
                    <img src="{{ message.sender.user_profile.get_mugshot_url }}" draggable="false"/>
                </div>
                <div class="msg">
                    <p>{{ message.content }}</p>
                    <time>{{ message.time }}</time>
                </div>
                </li>
                {% endfor %}
            </ol>

            <ol class="chat" id="new-message"></ol>

        </div>

        <div class="input-field col s6">
            <i class="material-icons prefix">mode_edit</i>
            <textarea id="field" class="materialize-textarea"></textarea>
            <label for="field">Message</label>
            <button class="waves-effect waves-light btn" onclick="send_message()">Send</button>
        </div>
    </div>
</div>

picme/accounts/templates/userena/email_confirm_complete.html
{% extends 'userena/profile_base.html' %}
{% load static %}


{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/profile_detail.css' %}" media="screen,projection">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" media="screen,projection">
{% endblock %}



{% block profile_content %}

<div class="container">
	<div class="row">
		<ul class="tabs tabs-fixed-width">
			<li class="tab col s3"><a target="_top" href="/accounts/{{user.username}}">User Profile</a></li>
			<li class="tab col s3"><a target="_top" href="/accounts/{{user.username}}/edit">Edit Profile</a></li>
			<li class="tab col s3"><a class="active" target="_top" href="/accounts/{{user.username}}/email">Change Email</a></li>
			<li class="tab col s4"><a target="_top" href="/accounts/{{user.username}}/password">Change Password</a></li>
		</ul>
	</div>
</div>


<div id="" class="card-panel">

	<ul class="collection">
	<p>Your new email address is saved. You can continue using {{ site.name }} with this email.</p>
	</ul>	

</div>


{% endblock %}

picme/accounts/templates/userena/email_form.html
{% extends 'userena/profile_base.html' %}
{% load static %}


{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/profile_detail.css' %}" media="screen,projection">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" media="screen,projection">
{% endblock %}



{% block profile_content %}

<div class="container">
	<div class="row">
		<ul class="tabs tabs-fixed-width">
			<li class="tab col s3"><a target="_top" href="/accounts/{{user.username}}">User Profile</a></li>
			<li class="tab col s3"><a target="_top" href="/accounts/{{user.username}}/edit">Edit Profile</a></li>
			<li class="tab col s3"><a class="active" target="_top" href="/accounts/{{user.username}}/email">Change Email</a></li>
			<li class="tab col s4"><a target="_top" href="/accounts/{{user.username}}/password">Change Password</a></li>
		</ul>
	</div>
</div>


<div id="" class="card-panel">

	<ul class="collection">
		<form id="emil_form" action="" method="post">
			{% csrf_token %}
			<li>
				<div class="collection-item avatar">
					<i class="material-icons circle">email</i>
					<div class="row">
						<div class="col m9">
							{{ form.email.label_tag }}
							{{ form.email }}
						</div>
						<div class="col m3 red-text">
							{{ form.email.errors }}
						</div>
					</div>
				</div>
			</li><br>
			
			<div class="row">
				<div class="col m9 center-align">
					<a class="black waves-effect waves-light btn " onclick="$('#emil_form').submit()">Save changes</a>
				</div>
			</div>
		
		</form>
	</ul>	
</div>



{% endblock %}

picme/accounts/templates/userena/follow.html
<li>
	
{% if user.username != profile.user.username %}
	<div class="divider"></div>
	{% if not profile.user in user.user_profile.follows.all %}
	
	<div>
		<form id="follow_form" method="post" action="{% url 'accounts:follow' %}">
		{% csrf_token %}
			
		<input  type="text" name="followId" hidden="" value="
		{{ profile.user.id }}" hidden>
		<p>
			<a class="waves-effect waves-light btn" onclick="$('#follow_form').submit()">Follow</a>
			{% if user.username != profile.user.username %}
                <a class="waves-effect waves-light btn pink" onclick="window.open('{% url 'private_chat:dialogs_detail' username=profile.user.username %}')">Chat</a>
        	{% endif %}
		</p>
		</form>
	</div>
	{% else %}
	<div>
		<form id="unfollow_form" method="post" action="{% url 'accounts:unfollow' %}">
		{% csrf_token %}
			
		<input  type="text" name="unfollowId" hidden="" value="{{ profile.user.id }}" hidden>
		<p>
			<a class="waves-effect waves-light btn" onclick="$('#unfollow_form').submit()">Unfollow</a>
			{% if user.username != profile.user.username %}
                <a class="waves-effect waves-light btn pink" onclick="window.open('{% url 'private_chat:dialogs_detail' username=profile.user.username %}')">Chat</a>
        	{% endif %}
		</p>
		</form>
	</div>
	{% endif %}
{% endif %}


</li>

picme/accounts/templates/userena/my_follows.html
<!-- My Follows -->
{% if profile.user == user %}
	<ul class="collection with-header">
		<li class="collection-header"><h4>People I follow</h4></li>
	{% if not user.user_profile.follows or user.user_profile.follows.count == 0  %}
		<li class="collection-item red-text text-lighten-2">You have followed no one</li>
	{% else %}
		{% for follow in user.user_profile.follows.all %}
			<li class="collection-item">
				<form id="unfollow_form" method="post" action="{% url 'accounts:unfollow' %}">
				{% csrf_token %}
					<div class="chip grey lighten-4">
						<a href="/accounts/{{ follow.username }}">
							<img src="{{ follow.user_profile.get_mugshot_url }}"  alt = "Userena Mugshot">
							{{ follow.username }}
						</a>
					</div>
					<input  type="text" name="unfollowId" hidden="" value="{{ follow.id }}" hidden>

					<a class="red-text lighten-2 waves-effect waves-light btn-flat right" onclick="$('#unfollow_form').submit()">Unfollow</a>
				</form>
			</li>
		{% endfor %}
	{% endif %}
	</ul>
{% endif %}

picme/accounts/templates/userena/password_complete.html
{% extends 'userena/profile_base.html' %}
{% load static %}


{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/profile_detail.css' %}" media="screen,projection">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" media="screen,projection">
{% endblock %}



{% block profile_content %}


<div id="change_pwd" class="card-panel">

	<ul class="collection">
	<h4>Your password has been changed.</h4>
	<p>From now on you can use your new password to signin.</p>
	</ul>	

</div>



{% endblock %}

picme/accounts/templates/userena/password_form.html
{% extends 'userena/profile_base.html' %}
{% load static %}


{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/profile_detail.css' %}" media="screen,projection">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" media="screen,projection">
{% endblock %}



{% block profile_content %}

<div class="container">
	<div class="row">
		<ul class="tabs tabs-fixed-width">
			<li class="tab col s3"><a target="_top" href="/accounts/{{user.username}}">User Profile</a></li>
			<li class="tab col s3"><a target="_top" href="/accounts/{{user.username}}/edit">Edit Profile</a></li>
			<li class="tab col s3"><a target="_top" href="/accounts/{{user.username}}/email">Change Email</a></li>
			<li class="tab col s4"><a class="active" target="_top" href="/accounts/{{user.username}}/password">Change Password</a></li>
		</ul>
	</div>
</div>


<div id="" class="card-panel">

	<ul class="collection">
		<form action="" method="post" id="password_form">
		{% csrf_token %}
			<li>
				<div class="collection-item avatar">

				{% for error in non_field_errors %}
      				<p><span class="red-text">{{error}}</span></p>
				{% endfor %}

				</div>
			</li>

			<li>
				<div class="collection-item avatar">
					<i class="material-icons circle">vpn_key</i>
					<p>
						<div class="row">
							<div class="col m9">
								{{ form.old_password.label_tag }}
								{{ form.old_password }}
							</div>
							<div class="col m3 red-text">
								{{ form.old_password.errors }}
							</div>
						</div>
					</p>
					<i class="material-icons circle">vpn_key</i>
					<p>
						<div class="row">
							<div class="col m9">
								{{ form.new_password1.label_tag }}
								{{ form.new_password1 }}
							</div>
							<div class="col m3 red-text">
								{{ form.new_password1.errors }}
							</div>
						</div>
					</p>
					<i class="material-icons circle">vpn_key</i>
					<p>
						<div class="row">
							<div class="col m9">
								{{ form.new_password2.label_tag }}
								{{ form.new_password2 }}
							</div>
							<div class="col m3 red-text">
								{{ form.new_password2.errors }}
							</div>
						</div>
					</p>
				</div>
			</li>
			
			<br>
			<div class="row">
				<div class="col s9 center-align">
					<a class="black waves-effect waves-light btn " onclick="$('#password_form').submit()">Save changes</a>
				</div>
			</div>
		</form>
	</ul>	

</div>



{% endblock %}

picme/accounts/templates/userena/password_reset_confirm_form.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load static %}

{% block title %}Sign In{% endblock %}


{% block meta %}
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/signin_form.css' %}" media="screen,projection">
{% endblock %}

{% block header %}
{% endblock %}


{% block content %}
<br><br><br>
<div class="hide-on-small-only">
	<br><br><br><br><br> 
</div>

<div class="row">
	<div class="card-panel col s12 m6 l6 offset-m3 offset-l3 transparentpad white-text z-depth-5">
		<!-- TAB -->
		<div >
			<ul class="tabs transparent">
				<li class="tab col s6"><a target="_self"  href="\accounts\signup">Sign Up</a></li>
				<li class="tab col s6"><a class="active"  href="#signin_form_div">Sign In</a></li>
			</ul>
		</div>

		<br>

		<div id="signin_form_div" class="col s12">
			<form id="passwd_reset_confirm_form" action="" method="post">
				{% csrf_token %}

				{% if form.non_field_errors %}
					<div class="card-panel  transparent">

						{% for error in form.non_field_errors %}
							<label >{{error}}</label>
							<!-- <div class="chip">
							    {{error}}
							    <i class="close material-icons">close</i>
							</div> -->
						{% endfor %}
					</div>
				{% endif %}
				
				
				{% for field in form %}
				
					<div class="row">
 						<div class="input-field col s12">
 							<div >
								{{ field.label_tag }}
								{{ field }}
								<div class="red-text">
									{{ field.errors }}
								</div>
							</div>
						</div>
					</div>
						
				{% endfor %}

				<p class="center-align ">
					<a class="grey lighten-3 waves-effect waves-light btn black-text" onclick="$('#passwd_reset_confirm_form').submit()">Reset</a>
				</p>

			</form>
			<br>
		</div>
		
	</div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}


{% block script %}
	<!-- <script type="text/javascript" src="{% static 'accounts/js/signin.js' %}"></script> -->
{% endblock %}

picme/accounts/templates/userena/password_reset_form.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load static %}

{% block title %}Sign In{% endblock %}


{% block meta %}
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/signin_form.css' %}" media="screen,projection">
{% endblock %}

{% block header %}
{% endblock %}


{% block content %}
<br><br><br>
<div class="hide-on-small-only">
	<br><br><br><br><br> 
</div>

<div class="row">
	<div class="card-panel col s12 m6 l6 offset-m3 offset-l3 transparentpad white-text z-depth-5">
		<!-- TAB -->
		<div >
			<ul class="tabs transparent">
				<li class="tab col s6"><a target="_self"  href="\accounts\signup">Sign Up</a></li>
				<li class="tab col s6"><a class="active"  href="#signin_form_div">Sign In</a></li>
			</ul>
		</div>

		<br>

		<div id="signin_form_div" class="col s12">
			<form id="passwd_reset_confirm_form" action="" method="post">
				{% csrf_token %}

				{% if form.non_field_errors %}
					<div class="card-panel  transparent">

						{% for error in form.non_field_errors %}
							<label >{{error}}</label>
							<!-- <div class="chip">
							    {{error}}
							    <i class="close material-icons">close</i>
							</div> -->
						{% endfor %}
					</div>
				{% endif %}
				
				
				{% for field in form %}
				
					<div class="row">
 						<div class="input-field col s12">
 							<div >
								{{ field.label_tag }}
								{{ field }}
								<div class="red-text">
									{{ field.errors }}
								</div>
							</div>
						</div>
					</div>
						
				{% endfor %}

				<p class="center-align ">
					<a class="grey lighten-3 waves-effect waves-light btn black-text" onclick="$('#passwd_reset_confirm_form').submit()">Send Request</a>
				</p>

			</form>
			<br>
		</div>
		
	</div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}


{% block script %}
	<!-- <script type="text/javascript" src="{% static 'accounts/js/signin.js' %}"></script> -->
{% endblock %}

picme/accounts/templates/userena/profile_base.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}{{ user.username }}'s Profile{% endblock %}

{% block meta %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/profile_base.css' %}" media="screen,projection">
    {% block css %}
    {% endblock %}
{% endblock %}

{% block content %}
	<div>
        <div id="profile_bg_img_container" class="card small z-depth-0 valign-wrapper" style="background-image: url('http://i.huffpost.com/gen/2299606/images/o-STARRY-NIGHT-facebook.jpg')">
            <div id="profile_mugshot_container" class="valign">
                {% if user.username == profile.user.username %}
                <img src="{{user.user_profile.get_mugshot_url}}" alt="" class="circle responsive-img z-depth-5">
                {% else %}
                <img src="{{profile.user.user_profile.get_mugshot_url}}" alt="" class="circle responsive-img z-depth-5">
                {% endif %}
            </div>
        </div>
        
        {% block profile_content %}

        {% endblock %}
        
    </div>
{% endblock %}

{% block script %}
<!-- <script type="text/javascript" src="{% static '/accounts/js/profile_sidebar.js' %}"></script> -->

{% block morescript %}
{% endblock %}

{% endblock %}

picme/accounts/templates/userena/profile_detail.html
{% extends 'userena/profile_base.html' %}
{% load static %}

{% block title %}{{ profile.user.username }}'s Profile{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/profile_detail.css' %}" media="screen,projection">
    <link rel="stylesheet" type="text/css"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" media="screen,projection">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/chat.css' %}">
{% endblock %}

{% block profile_content %}

    {% if user.username == profile.user.username %}
        <div class="container">
            <div class="row">
                <ul class="tabs tabs-fixed-width">
                    <li class="tab col s3"><a class="active" target="_top" href="/accounts/{{ user.username }}">User
                        Profile</a></li>
                    <li class="tab col s3"><a target="_top" href="/accounts/{{ user.username }}/edit">Edit Profile</a>
                    </li>
                    <li class="tab col s3"><a target="_top" href="/accounts/{{ user.username }}/email">Change Email</a>
                    </li>
                    <li class="tab col s4"><a target="_top" href="/accounts/{{ user.username }}/password">Change
                        Password</a></li>
                </ul>
            </div>
        </div>
    {% endif %}

    <div id="profile_div" class="card-panel">
        <ul class="collection">
            <li>
                <div class="collection-item avatar">
                    <i class="material-icons circle ">perm_identity</i>
                    <span class="title">
					User Name:
				</span>
                    <p>
                        {{ profile.user.username }}
                    </p>
                </div>
            </li>
            <li>
                <div class="collection-item avatar">
                    <i class="fa fa-user-circle circle" aria-hidden="true"></i>
                    <span class="title">
					Nick Name:
				</span>
                    <p>
                        {{ profile.user.user_profile.nick_name }}
                    </p>
                </div>
            </li>
            <li>
                <div class="collection-item avatar">
                    <i class="material-icons circle ">insert_chart</i>
                    <span class="title">
					Description:
				</span>
                    <p>
                        {{ profile.user.user_profile.description }}
                    </p>
                </div>
            </li>
            <li>
                <div class="collection-item avatar">
                    <i class="fa fa-venus-mars circle" aria-hidden="true"></i>
                    <span class="title">
					Gender:
				</span>
                    <p>
                        {{ profile.user.user_profile.get_gender_display }}
                    </p>
                </div>
            </li>

            <li>
                <div class="collection-item avatar">
                    <i class="material-icons circle">email</i>
                    <span class="title">
					Email:
				</span>
                    <p>
                        {{ profile.user.email }}
                    </p>
                </div>
            </li>

            {% include "userena/follow.html" %}

        </ul>

    </div>

    {% include "userena/my_follows.html" %}

    <div class="card-panel"> 
        <div id="map_wrapper">
            <div id="map_canvas" class="mapping"></div>
        </div>
    </div>

{% include "userena/chatModal.html" %}

{% endblock %}

{% block morescript %}
    <script type="text/javascript"> 
        var user_id = "{{profile.user.id}}";
    </script>
    <script src="{% static 'accounts/js/map.js' %}"></script>
    <script type="text/javascript" src="{% static 'accounts/js/chat.js' %}"></script>
    
{% endblock %}

picme/accounts/templates/userena/profile_form.html
{% extends 'userena/profile_base.html' %}
{% load static %}


{% block script %}
    <script src="{% static 'accounts/js/profile_form.js' %}" type="text/javascript"></script>
{% endblock %}


{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/profile_detail.css' %}" media="screen,projection">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" media="screen,projection">
{% endblock %}



{% block profile_content %}

<div class="container">
	<div class="row">
		<ul class="tabs tabs-fixed-width">
			<li class="tab col s3"><a target="_top" href="/accounts/{{user.username}}">User Profile</a></li>
			<li class="tab col s3"><a class="active" target="_top" href="/accounts/{{user.username}}/edit">Edit Profile</a></li>
			<li class="tab col s3"><a target="_top" href="/accounts/{{user.username}}/email">Change Email</a></li>
			<li class="tab col s4"><a target="_top" href="/accounts/{{user.username}}/password">Change Password</a></li>
		</ul>
	</div>
</div>


<div id="profile_edit" class="card-panel">

	<ul class="collection">
		<form id="profile_edit_form" action="" enctype="multipart/form-data" method="post">
			{% csrf_token %}
			<li>
				<div class="collection-item avatar">
					<i class="fa fa-user-circle circle" aria-hidden="true"></i>
					<label for="id_nick_name">
						Nick Name:
					</label>
					<p>
		    		<div class="row">
	      				<div class="col s9">{{form.nick_name}}</div>
						<div class="col s3">{{form.nick_name.error}}</div>
					</div>
					</p>
				</div>
			</li>
			<li>
				<div class="collection-item avatar">
					<i class="material-icons circle ">perm_media</i>
					<label for="id_mugshot">
						Mugshot:
					</label>
					<div class="row">
						<div class="file-field input-field col s9">
							<div class="grey darken-2 waves-effect waves-light btn">
							<span>New Mugshot</span>
							<input id="id_mugshot" name='mugshot' type="file">
							</div>
							<div class="file-path-wrapper">
							<input class="file-path validate" type="text">
							</div>	
							{{form.mugshot.error}}
						</div>
					</div>
				</div>

			</li>
			<li>
				<div class="collection-item avatar">
					<br>
					<i class="material-icons circle ">insert_chart</i>
					<label for="id_description">
						Description:
					</label>
					<p>
		    		<div class="row">
						<div class="col s9">{{form.description}}</div>
						<div class="col s3">{{form.description.error}}</div>
					</div>
					</p>
				</div>
			</li>
			<li>
				<div class="collection-item avatar">
					<i class="fa fa-venus-mars circle" aria-hidden="true"></i>
					<label for="id_gender">
						Gender:
					</label>
					<p>
					<div class="row">
						<div class="col s9">{{form.gender}}</div>
						<div class="col s3">{{form.gender.error}}</div>
					</div>
					</p>
				</div>
			</li>

			<br>
			<div class="hide">
				{{ form.privacy }}
			</div>
			<div class="row">
				<div class="col s9 center-align">
					<a class="black waves-effect waves-light btn " onclick="$('#profile_edit_form').submit()">Save changes</a>
				</div>
			</div>
			
			<br>
		</form>
	</ul>	

</div>



{% endblock %}